pi_esprit_message:
    resource: "@PiEspritMessageBundle/Resources/config/routing.yml"
    prefix:   /

pi_esprit_user:
    resource: "@PiEspritUserBundle/Resources/config/routing.yml"
    prefix:   /

pi_esprit_covoiturage:
    resource: "@PiEspritCovoiturageBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@PiEspritUserBundle/Resources/config/routing.yml"
    prefix:   /

covoiturage:
    resource: "@PiEspritCovoiturageBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# app/config/routing.yml

fos_message:
    resource: "@PiEspritMessageBundle/Resources/config/routing.xml"
    prefix: /msg
