covoiturage_user:
    resource: "@CovoiturageUserBundle/Resources/config/routing.yml"
    prefix:   /

covoiturage:
    resource: "@CovoiturageBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
