covoiturage_homepage:
    path:     /
    defaults: { _controller: CovoiturageBundle:Default:index }

Accueil:
    path:     /index
    defaults: { _controller: CovoiturageBundle:User:accueil }

Trajets:
    path:     /trajets
    defaults: { _controller: CovoiturageBundle:User:trajets }

About:
    path:     /about
    defaults: { _controller: CovoiturageBundle:User:about }

Contact:
    path:     /contact
    defaults: { _controller: CovoiturageBundle:User:contact }

FAQ:
    path:     /FAQ
    defaults: { _controller: CovoiturageBundle:User:faq }

Promos:
    path:     /promos
    defaults: { _controller: CovoiturageBundle:User:promos }

Admin:
    path:     /dashboard
    defaults: { _controller: CovoiturageBundle:Admin:accueil }

Profil:
    path:     /profil
    defaults: { _controller: CovoiturageBundle:User:profil }

ListQuiz:
    path:     /listquiz
    defaults: { _controller: CovoiturageBundle:Admin:list }
